server:
  port: 443
  redirect:
    from: 80
    to: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/multishop.p12
    key-store-password: AsadMasad@1366
    key-alias: multishop
    enabled: true
login:
  redirect:
    url: https://piana.ir
