server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/multishop.p12
    key-store-password: AsadMasad@1366
    key-alias: multishop
    enabled: true
  servlet:
    encoding:
      force-response: true
spring:
  profiles:
#    include: resources, store, production, develop
    include: resources, store, production, product
#    include: resources, store, production
#  config:
#    activate:
#      on-profile: resources, production
  servlet:
    multipart:
      max-file-size: 2048KB
      max-request-size: 2048KB
  resources:
    cache: false
    cache.period: 0
  template:
    cache: false
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  datasource:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO
    com.rh: INFO
  pattern:
    file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  file:
    path: ./application.log
database:
  show-sql: true
  pool-size: 5
  support:
    url: jdbc:h2:file:./data/support
#    url: jdbc:h2:mem:site
#    url: jdbc:oracle:thin:@192.168.2.111:1521/site
    username: support
    password: s
    driverClassName: org.h2.Driver
#    driverClassName: oracle.jdbc.OracleDriver
  packages-to-scan:
    - ir.piana.business.prediction.common.data.entity
    - ir.piana.business.prediction.module.**.data.entity
